import { ref, computed } from 'vue'

const STORAGE_KEY = 'tc-sports-language'

const translations = {
  en: {
    nav: {
      home: "Home",
      register: "Register",
      interests: "Interests",
      liveFeed: "Live Feed",
      matches: "Matches",
      shop: "Shop",
      myArchive: "My Archive",
      preferences: "Preferences",
      navigation: "Navigation",
      theme: "Theme",
      login: "Login",
    },
    user: {
      profileSettings: "Profile Settings",
      signOut: "Sign Out",
      signIn: "Sign In",
      language: "Language",
    },
    home: {
      welcome: "Welcome to",
      description: "Stay updated with the latest news, scores, and articles about your favorite sports and athletes.",
      getStarted: "Get Started",
      browseArticles: "Browse Articles",
      features: {
        personalized: "Personalized Feed",
        personalizedDesc: "Get news tailored to your favorite sports and teams",
        liveUpdates: "Live Updates",
        liveUpdatesDesc: "Real-time scores and breaking news as it happens",
        archive: "Save & Archive",
        archiveDesc: "Save articles to read later and build your collection",
      },
      ticker: {
        matches: "Live Matches",
        standings: "Standings",
        viewAll: "View all",
      },
      latestNews: "Latest News",
      team: "Team",
    },
    register: {
      title: "Create Account",
      subtitle: "Join TC Sports to personalize your sports news experience",
      fullName: "Full Name",
      fullNamePlaceholder: "Enter your full name",
      email: "Email",
      emailPlaceholder: "Enter your email",
      password: "Password",
      passwordPlaceholder: "Create a password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm your password",
      createAccount: "Create Account",
      creating: "Creating account...",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
      passwordMinLength: "Password must be at least 8 characters",
      passwordsNoMatch: "Passwords do not match",
      successTitle: "Account created!",
      successMessage: "Please check your email to confirm your account.",
    },
    interests: {
      title: "Select Your Interests",
      subtitle: "Choose the sports you want to follow. We'll personalize your feed based on your selections.",
      selected: "selected",
      saveInterests: "Save Interests",
      saving: "Saving...",
      successTitle: "Interests saved!",
      successMessage: "Your feed will now be personalized based on your selections.",
    },
    liveFeed: {
      title: "Live Feed",
      subtitle: "Latest sports news and articles",
      searchPlaceholder: "Search articles...",
      allSports: "All Sports",
      myInterests: "My Interests",
      noArticles: "No articles found",
      noArticlesDesc: "Try adjusting your search or filter criteria",
      clearFilters: "Clear filters",
    },
    article: {
      backToFeed: "Back to Feed",
      share: "Share",
      copyLink: "Copy link",
      linkCopied: "Link copied!",
      shareOnFacebook: "Share on Facebook",
      shareOnWhatsApp: "Share on WhatsApp",
      saveToArchive: "Save to archive",
      removeFromArchive: "Remove from archive",
      by: "By",
      tags: "Tags",
      relatedArticles: "Related Articles",
      popularTags: "Popular Tags",
      articleNotFound: "Article not found",
      articleNotFoundDesc: "The article you're looking for doesn't exist or has been removed.",
    },
    archive: {
      title: "My Archive",
      subtitle: "Articles you've saved for later",
      archivedOn: "Archived on",
      remove: "Remove",
      emptyTitle: "Your archive is empty",
      emptyDesc: "Save articles from the Live Feed to read later",
      browseFeed: "Browse Live Feed",
    },
    profile: {
      title: "Profile Settings",
      subtitle: "Manage your account settings and password",
      accountInfo: "Account Information",
      accountInfoDesc: "Your basic account details",
      fullName: "Full Name",
      email: "Email",
      changePassword: "Change Password",
      changePasswordDesc: "Update your password to keep your account secure",
      currentPassword: "Current Password",
      currentPasswordPlaceholder: "Enter current password",
      newPassword: "New Password",
      newPasswordPlaceholder: "Enter new password",
      confirmNewPassword: "Confirm New Password",
      confirmNewPasswordPlaceholder: "Confirm new password",
      updatePassword: "Update Password",
      updating: "Updating...",
      passwordMinLength: "New password must be at least 8 characters",
      passwordsNoMatch: "New passwords do not match",
      successMessage: "Your password has been changed successfully.",
    },
    preferences: {
      title: "Preferences",
      subtitle: "Customize your TC Sports experience",
      notifications: "Notifications",
      notificationsDesc: "Manage how you receive updates",
      emailNotifications: "Email Notifications",
      emailNotificationsDesc: "Receive updates via email",
      pushNotifications: "Push Notifications",
      pushNotificationsDesc: "Receive push notifications in your browser",
      breakingNews: "Breaking News Alerts",
      breakingNewsDesc: "Get notified about major sports events",
      weeklyDigest: "Weekly Digest",
      weeklyDigestDesc: "Receive a weekly summary of top stories",
      content: "Content",
      contentDesc: "Customize your content preferences",
      articlesPerPage: "Articles Per Page",
      autoPlayVideos: "Auto-play Videos",
      autoPlayVideosDesc: "Automatically play videos in articles",
      showLiveScores: "Show Live Scores",
      showLiveScoresDesc: "Display live scores in the sidebar",
      privacy: "Privacy",
      privacyDesc: "Control your privacy settings",
      shareActivity: "Share Activity",
      shareActivityDesc: "Allow others to see your reading activity",
      personalizedAds: "Personalized Ads",
      personalizedAdsDesc: "Show ads based on your interests",
      merchandise: "Merchandise",
      merchandiseDesc: "Exclusive merchandise opportunities",
      lotteryOptIn: "Opt-in for merchandise lottery",
      lotteryOptInDesc: "Become eligible for personalized merch from sporters based on your personal interests and archive",
      lotteryNotice: "Next lottery draw: February 7, 2026 — Good luck!",
      savePreferences: "Save Preferences",
      successTitle: "Saved!",
    },
    sports: {
      football: "Football",
      basketball: "Basketball",
      tennis: "Tennis",
      cycling: "Cycling",
      swimming: "Swimming",
      formula1: "Formula 1",
      golf: "Golf",
      rugby: "Rugby",
      baseball: "Baseball",
      hockey: "Hockey",
      volleyball: "Volleyball",
      boxing: "Boxing",
    },
    common: {
      loading: "Loading...",
      poweredBy: "Powered by",
      and: "and",
    },
    login: {
      title: "Sign In",
      subtitle: "Sign in to access your personalized sports feed",
      email: "Email",
      password: "Password",
      signIn: "Sign In",
      noAccount: "Don't have an account?",
      register: "Register",
    },
    shop: {
      title: "Team Shop",
      subtitle: "Official merchandise from your favorite teams",
      filterByTeam: "Filter by team",
      allProducts: "All",
      clothing: "Clothing",
      accessories: "Accessories",
      equipment: "Equipment",
      addToCart: "Add to Cart",
      addedToCart: "Added to cart!",
      noProducts: "No products found",
      noProductsDesc: "Try selecting a different team or category",
    },
    matches: {
      all: "All",
      live: "Live",
      fullTime: "Full-time",
      scheduled: "Scheduled",
      myTeams: "My Teams",
      today: "Today",
      allLeagues: "All Leagues",
      standings: "Standings",
      noMatches: "No matches found for selected filters",
      match: "Match",
      odds: "Odds",
      h2h: "H2H",
      summary: "Summary",
      lineups: "Lineups",
      overUnder: "Over/Under",
      btts: "BTTS",
      analysis: "Analysis",
      matchPreview: "Match Preview",
      round: "Round",
      viewMatch: "View Match",
      matchStartingSoon: "Match Starting Soon",
      kicksOffIn: "kicks off in",
      minutes: "minutes",
      goal: "Goal",
      viewFullStandings: "View full standings",
    },
  },
  fr: {
    nav: {
      home: "Accueil",
      register: "S'inscrire",
      interests: "Centres d'intérêt",
      liveFeed: "Fil d'actualité",
      matches: "Matchs",
      shop: "Boutique",
      myArchive: "Mes archives",
      preferences: "Préférences",
      navigation: "Navigation",
      theme: "Thème",
      login: "Connexion",
    },
    user: {
      profileSettings: "Paramètres du profil",
      signOut: "Se déconnecter",
      signIn: "Se connecter",
      language: "Langue",
    },
    home: {
      welcome: "Bienvenue sur",
      description: "Restez informé des dernières nouvelles, scores et articles sur vos sports et athlètes préférés.",
      getStarted: "Commencer",
      browseArticles: "Parcourir les articles",
      features: {
        personalized: "Fil personnalisé",
        personalizedDesc: "Recevez des actualités adaptées à vos sports préférés",
        liveUpdates: "Mises à jour en direct",
        liveUpdatesDesc: "Scores en temps réel et actualités de dernière minute",
        archive: "Sauvegarder et archiver",
        archiveDesc: "Enregistrez des articles pour plus tard",
      },
      ticker: {
        matches: "Matchs en direct",
        standings: "Classement",
        viewAll: "Voir tout",
      },
      latestNews: "Dernières actualités",
      team: "Équipe",
    },
    register: {
      title: "Créer un compte",
      subtitle: "Rejoignez TC Sports pour personnaliser votre expérience",
      fullName: "Nom complet",
      fullNamePlaceholder: "Entrez votre nom complet",
      email: "E-mail",
      emailPlaceholder: "Entrez votre e-mail",
      password: "Mot de passe",
      passwordPlaceholder: "Créez un mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      confirmPasswordPlaceholder: "Confirmez votre mot de passe",
      createAccount: "Créer un compte",
      creating: "Création en cours...",
      haveAccount: "Vous avez déjà un compte?",
      signIn: "Se connecter",
      passwordMinLength: "Le mot de passe doit contenir au moins 8 caractères",
      passwordsNoMatch: "Les mots de passe ne correspondent pas",
      successTitle: "Compte créé!",
      successMessage: "Vérifiez votre e-mail pour confirmer votre compte.",
    },
    interests: {
      title: "Sélectionnez vos centres d'intérêt",
      subtitle: "Choisissez les sports que vous souhaitez suivre.",
      selected: "sélectionné(s)",
      saveInterests: "Enregistrer",
      saving: "Enregistrement...",
      successTitle: "Intérêts enregistrés!",
      successMessage: "Votre fil sera personnalisé.",
    },
    liveFeed: {
      title: "Fil d'actualité",
      subtitle: "Dernières actualités et articles sportifs",
      searchPlaceholder: "Rechercher des articles...",
      allSports: "Tous les sports",
      myInterests: "Mes intérêts",
      noArticles: "Aucun article trouvé",
      noArticlesDesc: "Essayez d'ajuster vos critères",
      clearFilters: "Effacer les filtres",
    },
    article: {
      backToFeed: "Retour au fil",
      share: "Partager",
      copyLink: "Copier le lien",
      linkCopied: "Lien copié!",
      shareOnFacebook: "Partager sur Facebook",
      shareOnWhatsApp: "Partager sur WhatsApp",
      saveToArchive: "Ajouter aux archives",
      removeFromArchive: "Retirer des archives",
      by: "Par",
      tags: "Tags",
      relatedArticles: "Articles associés",
      popularTags: "Tags populaires",
      articleNotFound: "Article non trouvé",
      articleNotFoundDesc: "L'article n'existe pas ou a été supprimé.",
    },
    archive: {
      title: "Mes archives",
      subtitle: "Articles enregistrés pour plus tard",
      archivedOn: "Archivé le",
      remove: "Supprimer",
      emptyTitle: "Vos archives sont vides",
      emptyDesc: "Enregistrez des articles du fil d'actualité",
      browseFeed: "Parcourir le fil",
    },
    profile: {
      title: "Paramètres du profil",
      subtitle: "Gérez vos paramètres de compte",
      accountInfo: "Informations du compte",
      accountInfoDesc: "Vos informations de base",
      fullName: "Nom complet",
      email: "E-mail",
      changePassword: "Changer le mot de passe",
      changePasswordDesc: "Mettez à jour votre mot de passe",
      currentPassword: "Mot de passe actuel",
      currentPasswordPlaceholder: "Entrez le mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      newPasswordPlaceholder: "Entrez le nouveau mot de passe",
      confirmNewPassword: "Confirmer le nouveau mot de passe",
      confirmNewPasswordPlaceholder: "Confirmez le nouveau mot de passe",
      updatePassword: "Mettre à jour",
      updating: "Mise à jour...",
      passwordMinLength: "Le mot de passe doit contenir au moins 8 caractères",
      passwordsNoMatch: "Les mots de passe ne correspondent pas",
      successMessage: "Mot de passe modifié avec succès.",
    },
    preferences: {
      title: "Préférences",
      subtitle: "Personnalisez votre expérience TC Sports",
      notifications: "Notifications",
      notificationsDesc: "Gérez vos mises à jour",
      emailNotifications: "Notifications par e-mail",
      emailNotificationsDesc: "Recevez des mises à jour par e-mail",
      pushNotifications: "Notifications push",
      pushNotificationsDesc: "Recevez des notifications push",
      breakingNews: "Alertes de dernière minute",
      breakingNewsDesc: "Soyez averti des événements majeurs",
      weeklyDigest: "Résumé hebdomadaire",
      weeklyDigestDesc: "Recevez un résumé hebdomadaire",
      content: "Contenu",
      contentDesc: "Personnalisez vos préférences",
      articlesPerPage: "Articles par page",
      autoPlayVideos: "Lecture automatique des vidéos",
      autoPlayVideosDesc: "Lire automatiquement les vidéos",
      showLiveScores: "Afficher les scores en direct",
      showLiveScoresDesc: "Afficher les scores dans la barre latérale",
      privacy: "Confidentialité",
      privacyDesc: "Contrôlez vos paramètres de confidentialité",
      shareActivity: "Partager l'activité",
      shareActivityDesc: "Permettre aux autres de voir votre activité",
      personalizedAds: "Publicités personnalisées",
      personalizedAdsDesc: "Afficher des publicités basées sur vos intérêts",
      merchandise: "Marchandise",
      merchandiseDesc: "Opportunités de marchandise exclusives",
      lotteryOptIn: "Participer à la loterie de marchandise",
      lotteryOptInDesc: "Devenez éligible pour des produits personnalisés de sportifs basés sur vos intérêts et archives",
      lotteryNotice: "Prochain tirage: 7 février 2026 — Bonne chance!",
      savePreferences: "Enregistrer",
      successTitle: "Enregistré!",
    },
    sports: {
      football: "Football",
      basketball: "Basketball",
      tennis: "Tennis",
      cycling: "Cyclisme",
      swimming: "Natation",
      formula1: "Formule 1",
      golf: "Golf",
      rugby: "Rugby",
      baseball: "Baseball",
      hockey: "Hockey",
      volleyball: "Volleyball",
      boxing: "Boxe",
    },
    common: {
      loading: "Chargement...",
      poweredBy: "Propulsé par",
      and: "et",
    },
    login: {
      title: "Connexion",
      subtitle: "Connectez-vous pour accéder à votre fil sportif personnalisé",
      email: "E-mail",
      password: "Mot de passe",
      signIn: "Se connecter",
      noAccount: "Vous n'avez pas de compte?",
      register: "S'inscrire",
    },
    shop: {
      title: "Boutique Équipe",
      subtitle: "Produits officiels de vos équipes préférées",
      filterByTeam: "Filtrer par équipe",
      allProducts: "Tous",
      clothing: "Vêtements",
      accessories: "Accessoires",
      equipment: "Équipement",
      addToCart: "Ajouter au panier",
      addedToCart: "Ajouté au panier!",
      noProducts: "Aucun produit trouvé",
      noProductsDesc: "Essayez de sélectionner une autre équipe ou catégorie",
    },
    matches: {
      all: "Tous",
      live: "En direct",
      fullTime: "Terminé",
      scheduled: "Programmé",
      myTeams: "Mes équipes",
      today: "Aujourd'hui",
      allLeagues: "Toutes les ligues",
      standings: "Classement",
      noMatches: "Aucun match trouvé pour les filtres sélectionnés",
      match: "Match",
      odds: "Cotes",
      h2h: "Confrontations",
      summary: "Résumé",
      lineups: "Compositions",
      overUnder: "Plus/Moins",
      btts: "LDE2",
      analysis: "Analyse",
      matchPreview: "Aperçu du match",
      round: "Journée",
      viewMatch: "Voir le match",
      matchStartingSoon: "Match bientôt",
      kicksOffIn: "coup d'envoi dans",
      minutes: "minutes",
      goal: "But",
      viewFullStandings: "Voir le classement complet",
    },
  },
  nl: {
    nav: {
      home: "Home",
      register: "Registreren",
      interests: "Interesses",
      liveFeed: "Live Feed",
      matches: "Wedstrijden",
      shop: "Winkel",
      myArchive: "Mijn Archief",
      preferences: "Voorkeuren",
      navigation: "Navigatie",
      theme: "Thema",
      login: "Inloggen",
    },
    user: {
      profileSettings: "Profielinstellingen",
      signOut: "Uitloggen",
      signIn: "Inloggen",
      language: "Taal",
    },
    home: {
      welcome: "Welkom bij",
      description: "Blijf op de hoogte van het laatste nieuws, scores en artikelen over je favoriete sporten.",
      getStarted: "Aan de slag",
      browseArticles: "Artikelen bekijken",
      features: {
        personalized: "Gepersonaliseerde Feed",
        personalizedDesc: "Ontvang nieuws afgestemd op je favoriete sporten",
        liveUpdates: "Live Updates",
        liveUpdatesDesc: "Realtime scores en breaking news",
        archive: "Opslaan en archiveren",
        archiveDesc: "Bewaar artikelen om later te lezen",
      },
      ticker: {
        matches: "Live wedstrijden",
        standings: "Stand",
        viewAll: "Bekijk alles",
      },
      latestNews: "Laatste nieuws",
      team: "Team",
    },
    register: {
      title: "Account aanmaken",
      subtitle: "Word lid van TC Sports om je ervaring te personaliseren",
      fullName: "Volledige naam",
      fullNamePlaceholder: "Voer je volledige naam in",
      email: "E-mail",
      emailPlaceholder: "Voer je e-mail in",
      password: "Wachtwoord",
      passwordPlaceholder: "Maak een wachtwoord",
      confirmPassword: "Wachtwoord bevestigen",
      confirmPasswordPlaceholder: "Bevestig je wachtwoord",
      createAccount: "Account aanmaken",
      creating: "Account aanmaken...",
      haveAccount: "Heb je al een account?",
      signIn: "Inloggen",
      passwordMinLength: "Wachtwoord moet minimaal 8 tekens bevatten",
      passwordsNoMatch: "Wachtwoorden komen niet overeen",
      successTitle: "Account aangemaakt!",
      successMessage: "Controleer je e-mail om je account te bevestigen.",
    },
    interests: {
      title: "Selecteer je interesses",
      subtitle: "Kies de sporten die je wilt volgen.",
      selected: "geselecteerd",
      saveInterests: "Interesses opslaan",
      saving: "Opslaan...",
      successTitle: "Interesses opgeslagen!",
      successMessage: "Je feed wordt nu gepersonaliseerd.",
    },
    liveFeed: {
      title: "Live Feed",
      subtitle: "Laatste sportnieuws en artikelen",
      searchPlaceholder: "Artikelen zoeken...",
      allSports: "Alle Sporten",
      myInterests: "Mijn Interesses",
      noArticles: "Geen artikelen gevonden",
      noArticlesDesc: "Probeer je criteria aan te passen",
      clearFilters: "Filters wissen",
    },
    article: {
      backToFeed: "Terug naar Feed",
      share: "Delen",
      copyLink: "Link kopiëren",
      linkCopied: "Link gekopieerd!",
      shareOnFacebook: "Delen op Facebook",
      shareOnWhatsApp: "Delen op WhatsApp",
      saveToArchive: "Opslaan in archief",
      removeFromArchive: "Verwijderen uit archief",
      by: "Door",
      tags: "Tags",
      relatedArticles: "Gerelateerde Artikelen",
      popularTags: "Populaire Tags",
      articleNotFound: "Artikel niet gevonden",
      articleNotFoundDesc: "Het artikel bestaat niet of is verwijderd.",
    },
    archive: {
      title: "Mijn Archief",
      subtitle: "Artikelen die je hebt bewaard",
      archivedOn: "Gearchiveerd op",
      remove: "Verwijderen",
      emptyTitle: "Je archief is leeg",
      emptyDesc: "Bewaar artikelen van de Live Feed",
      browseFeed: "Live Feed bekijken",
    },
    profile: {
      title: "Profielinstellingen",
      subtitle: "Beheer je accountinstellingen",
      accountInfo: "Accountinformatie",
      accountInfoDesc: "Je basis accountgegevens",
      fullName: "Volledige naam",
      email: "E-mail",
      changePassword: "Wachtwoord wijzigen",
      changePasswordDesc: "Werk je wachtwoord bij",
      currentPassword: "Huidig wachtwoord",
      currentPasswordPlaceholder: "Voer huidig wachtwoord in",
      newPassword: "Nieuw wachtwoord",
      newPasswordPlaceholder: "Voer nieuw wachtwoord in",
      confirmNewPassword: "Nieuw wachtwoord bevestigen",
      confirmNewPasswordPlaceholder: "Bevestig nieuw wachtwoord",
      updatePassword: "Wachtwoord bijwerken",
      updating: "Bijwerken...",
      passwordMinLength: "Wachtwoord moet minimaal 8 tekens bevatten",
      passwordsNoMatch: "Wachtwoorden komen niet overeen",
      successMessage: "Je wachtwoord is succesvol gewijzigd.",
    },
    preferences: {
      title: "Voorkeuren",
      subtitle: "Pas je TC Sports ervaring aan",
      notifications: "Meldingen",
      notificationsDesc: "Beheer hoe je updates ontvangt",
      emailNotifications: "E-mailmeldingen",
      emailNotificationsDesc: "Ontvang updates via e-mail",
      pushNotifications: "Pushmeldingen",
      pushNotificationsDesc: "Ontvang pushmeldingen",
      breakingNews: "Breaking News Alerts",
      breakingNewsDesc: "Word gewaarschuwd over grote evenementen",
      weeklyDigest: "Wekelijkse Samenvatting",
      weeklyDigestDesc: "Ontvang een wekelijks overzicht",
      content: "Inhoud",
      contentDesc: "Pas je inhoudsvoorkeuren aan",
      articlesPerPage: "Artikelen per pagina",
      autoPlayVideos: "Video's automatisch afspelen",
      autoPlayVideosDesc: "Speel video's automatisch af",
      showLiveScores: "Live Scores tonen",
      showLiveScoresDesc: "Toon live scores in de zijbalk",
      privacy: "Privacy",
      privacyDesc: "Beheer je privacy-instellingen",
      shareActivity: "Activiteit delen",
      shareActivityDesc: "Sta anderen toe je activiteit te zien",
      personalizedAds: "Gepersonaliseerde advertenties",
      personalizedAdsDesc: "Toon advertenties op basis van je interesses",
      merchandise: "Merchandise",
      merchandiseDesc: "Exclusieve merchandise mogelijkheden",
      lotteryOptIn: "Doe mee aan de merchandise loterij",
      lotteryOptInDesc: "Word in aanmerking voor gepersonaliseerde merch van sporters op basis van je interesses en archief",
      lotteryNotice: "Volgende trekking: 7 februari 2026 — Veel succes!",
      savePreferences: "Voorkeuren opslaan",
      successTitle: "Opgeslagen!",
    },
    sports: {
      football: "Voetbal",
      basketball: "Basketbal",
      tennis: "Tennis",
      cycling: "Wielrennen",
      swimming: "Zwemmen",
      formula1: "Formule 1",
      golf: "Golf",
      rugby: "Rugby",
      baseball: "Honkbal",
      hockey: "Hockey",
      volleyball: "Volleybal",
      boxing: "Boksen",
    },
    common: {
      loading: "Laden...",
      poweredBy: "Mogelijk gemaakt door",
      and: "en",
    },
    login: {
      title: "Inloggen",
      subtitle: "Log in om je gepersonaliseerde sportfeed te bekijken",
      email: "E-mail",
      password: "Wachtwoord",
      signIn: "Inloggen",
      noAccount: "Nog geen account?",
      register: "Registreren",
    },
    shop: {
      title: "Team Winkel",
      subtitle: "Officiële merchandise van je favoriete teams",
      filterByTeam: "Filter op team",
      allProducts: "Alle",
      clothing: "Kleding",
      accessories: "Accessoires",
      equipment: "Uitrusting",
      addToCart: "In winkelwagen",
      addedToCart: "Toegevoegd aan winkelwagen!",
      noProducts: "Geen producten gevonden",
      noProductsDesc: "Probeer een ander team of categorie te selecteren",
    },
    matches: {
      all: "Alle",
      live: "Live",
      fullTime: "Afgelopen",
      scheduled: "Gepland",
      myTeams: "Mijn teams",
      today: "Vandaag",
      allLeagues: "Alle competities",
      standings: "Stand",
      noMatches: "Geen wedstrijden gevonden voor geselecteerde filters",
      match: "Wedstrijd",
      odds: "Odds",
      h2h: "Onderling",
      summary: "Samenvatting",
      lineups: "Opstellingen",
      overUnder: "Meer/Minder",
      btts: "BTS",
      analysis: "Analyse",
      matchPreview: "Wedstrijdvooruitblik",
      round: "Speeldag",
      viewMatch: "Bekijk wedstrijd",
      matchStartingSoon: "Wedstrijd begint binnenkort",
      kicksOffIn: "aftrap over",
      minutes: "minuten",
      goal: "Doelpunt",
      viewFullStandings: "Bekijk volledige stand",
    },
  },
}

const language = ref(localStorage.getItem(STORAGE_KEY) || 'en')

export function useLanguage() {
  const setLanguage = (lang) => {
    language.value = lang
    localStorage.setItem(STORAGE_KEY, lang)
  }

  const t = computed(() => translations[language.value] || translations.en)

  return {
    language,
    setLanguage,
    t,
    languages: [
      { code: 'en', name: 'English' },
      { code: 'fr', name: 'Français' },
      { code: 'nl', name: 'Nederlands' },
    ]
  }
}

